name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: sam build
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: "build"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: same package
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: "package --s3-bucket lambda-hot-deals --output-template-file packaged.yaml"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: sam deploy
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: "deploy --template-file packaged.yaml --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_DEFAULT_REGION }} --stack-name HotUkDeals-NewElectronicDeals-Lambda --parameter-overrides TelegramBotToken=${{ secrets.TELEGRAM_BOT_TOKEN }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
